version: "3.8"

services:
    elasticsearch:
        image: elasticsearch:7.13.4
        container_name: es01
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - elastic
        environment:
            node.name:  es01
            # cluster.name: es-docker-cluster
            # cluster.initial_master_nodes: es01
            discovery.type: single-node
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        healthcheck:
            test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
            interval: 10s
            timeout: 10s
            retries: 3
        volumes: 
            - data01:/usr/share/elasticsearch/data

    kibana:
        image: kibana:7.13.4
        container_name: kib01
        ports: 
            - 5601:5601
        environment: 
            ELASTICSEARCH_URL: http://es01:9200
            ELASTICSEARCH_HOSTS: http://es01:9200
        networks: 
            - elastic
        depends_on:
            - elasticsearch

networks:
  elastic:
    driver: bridge

volumes: 
    data01:
        driver: local

